### ISSUE TITLE
Style of item gets recycled

### ISSUE THREAD

**Issue by naraB** [marcocesarato/react-native-big-list#13]
Hi Marco, thank you so much for this great list.

My problem is: I have a list with selectable items, so the style of an item inside of the list depends on a local state (meaning the state is defined inside of the item component). If, for example, I select the first item in the list, its style gets changed but when I scroll down every 21st item is selected and its style is also changed event though I did not select those items. I know that this happens because of the recycling mechanism. 

How would you solve this problem?

**Comment by marcocesarato** [comment]
Hi @naraB, it's very simple. 
Here an example:

```js
import React, { useState } from "react";
import BigList from "react-native-big-list";
import { Checkbox } from "react-native-paper";

const data = [
    {label: '1', value: 1},
    {label: '2', value: 2},
    {label: '3', value: 3},
    {label: '4', value: 4},
    {label: '5', value: 5},
    {label: '6', value: 6}
]

const SelectList = () => {
  const [selected, setSelected] = useState();
  const renderItem = ({ item }) => {
    return (
      <Checkbox.Item
        key={item.value}
        mode="ios"
        label={item.label}
        status={selected === item.value ? "checked" : "unchecked"}
        onPress={() => setSelected(item.value)}
      />
    );
  };

  return <BigList data={data} renderItem={renderItem} rowHeight={50} />
};

export default SelectList;
```

I'll publish also it on demo the example as demostration.

**Comment by naraB** [comment]
With this example, every currently visible item gets rerendered. I tried using `React.memo(..)` with a custom propsAreEqual function to only rerender affected items but that seems to cause unexpected behavior

**Comment by marcocesarato** [comment]
> With this example, every currently visible item gets rerendered. I tried using `React.memo(..)` with a custom `propsAreEqual` function to only rerender affected items but that seems to cause unexpected behavior.
> Is there a way to use `React.memo(ListItem, (prev, next) => prev.rerender === next.rerender)` with react-native-big-list?
> `React.memo` seems to only be not causing unexpected behavior when comparing the whole props object, like this: `React.memo(ListItem, (prev, next) => prev === next)` which rerenders every visible item as well.

You mean that item are rerendered when you scroll (that is normal because the parent view is recycled but what is inside is destroyed), or rerendered because the example is single item selectable (that is normal because you need to update the others selected items to unchecked the previous checked). 

Instead if you meaning that you can select more than one item just move the selection state logic inside it. Like here:

```js
import React, { useState } from "react";
import BigList from "react-native-big-list";
import { Checkbox } from "react-native-paper";

const data = [
  {label: '1', value: 1},
  {label: '2', value: 2},
  {label: '3', value: 3},
  {label: '4', value: 4},
  {label: '5', value: 5},
  {label: '6', value: 6}
];

const ListItem = ({ item, onSelect }) => {
  const [selected, setSelected] = useState();
  return (
    <Checkbox.Item
      mode="ios"
      label={item.title}
      status={selected ? "checked" : "unchecked"}
      onPress={() => {
        setSelected(!selected);
        onSelect(item.value, !selected);
      }}
    />
  );
};

const SelectList = () => {
  const onSelect = (value, selected) => {
    // TODO: your logics
    console.log(
      "The value",
      value,
      "is " + (selected ? "selected" : "unselected"),
    );
  };
  const renderItem = ({ item }) => {
    return <ListItem item={item} onSelect={onSelect} />;
  };

  return <BigList data={data} renderItem={renderItem} rowHeight={50} />;
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default SelectList;
```

**Comment by naraB** [comment]
Sorry @marcocesarato, I should have created a snack to make sure you understand what I mean. 

Please have a look at this https://snack.expo.io/@narab/big-list-example

**Comment by marcocesarato** [comment]
As said before, this is normal because the parent view is recycled, so when the batch of visible items changes, the item view mantain its internal state, but its children are destroyed (`renderItem` view) and their state as well.

However when updating the selected element the state of all visible elements must change (to detect whether the element is selected or not) and then must be render again because all elements must be controlled by a state over the list (because the state of children will be destroyed during recycling and then lost).

This recycle method improve memory performances over thousands items, but yes they re-render everytime you change the global state. To re-render less items at once (if you have a heavy item view) you can set `batchSizeThreshold` to `0.5` (min value).

The difference from FlatList is that you re-render only visible items and not all items loaded before because FlatList increment the number of views loaded when you scroll, instead this list mantain the same number of views when you scroll because are recycled.
