### ISSUE TITLE
bug / contentContainerStyle is also affecting renderHeader

### ISSUE THREAD

**Issue by dougg0k** [marcocesarato/react-native-big-list#6]
`contentContainerStyle` is also affecting `renderHeader`, would be the same thing as just wrapping BigList in a View. So, it's not working only in the content.

**Comment by dougg0k** [comment]
Would be too hard to give the lib consumer a prop so he would choose to make `renderHeader` a part or not, of the recycle list content?

**Comment by marcocesarato** [comment]
> `contentContainerStyle` is also affecting `renderHeader`, would be the same thing as just wrapping BigList in a View. So, it's not working only in the content.

Yes, it's normal isn't a bug. Anyway send your mockup about your expectation.

> Would be too hard to give the lib consumer a prop so he would choose to make `renderHeader` a part or not, of the recycle list content? In my case the renderHeader is a bit heavier than normal, that could be the same situation for others.
> 
> In FlatList for example the only way is using their renderHeader alternative to have FlatList in a screen, otherwise would need to wrap all in a ScrollView, and that make FlatList pointless.

Maybe could be possibile only for Header and Footer. I need to try it and after I'll give you a feedback about it.

**Comment by dougg0k** [comment]
I mean, would be cool to have separate styling option props, one for the `renderHeader` and another for the `renderItem` list which already is the `contentContainerStyle`. I think that's how FlatList work. 

https://reactnative.dev/docs/flatlist#listheadercomponentstyle 
It also has a separate style obj for the footer. https://reactnative.dev/docs/flatlist#listfootercomponentstyle

**Comment by marcocesarato** [comment]
> I mean, would be cool to have separate styling option as props, one for the `renderHeader` and another for the `renderItem` list which already is the `contentContainerStyle`. I think that's how FlatList work.
> 
> In FlatList `contentContainerStyle` does not affect header nor footer.
> 
> https://reactnative.dev/docs/flatlist#listheadercomponentstyle
> It also has a separate style obj for the footer. https://reactnative.dev/docs/flatlist#listfootercomponentstyle

I add a static header and footer, so they shouldn't be re-rendered. To be released.

About `ListFooterComponentStyle` and `ListHeaderComponentStyle` already exists if you use `ListHeaderComponent` or `ListFooterComponent` but they are not really needed because your children can be styled with `flex: 1` to nullify the parent and the `width` and `height` can't be changed (for calculate the height of the view using processor) and they are available only for compatibility. `columnWrapperStyle` can be implemented but, as for `ListFooterComponentStyle`, I mustto overwrite height and width so its only for compatibility.

**Comment by dougg0k** [comment]
Nice, thanks.
